"""
Command handlers for HPJ bot.
"""

__all__ = (
    'ALL_COMMAND_HANDLERS',
    'ALARM_CONVO_HANDLER',
    'ALARM_CANCEL_HANDLER',
    'START_HANDLER',
    'HELP_HANDLER',
    'LOAD_HANDLER',
    'LOAD_CALLBACK_HANDLER',
    'SURVEY_CONVO_HANDLER',
    'ERROR_HANDLER',
    'ALARM_HOOK_HANDLER',
    'REPORT_HOOK_HANDLER',
)

from telegram.ext import BaseHandler

from .alarm import ALARM_CONVO_HANDLER, ALARM_CANCEL_HANDLER
from .error import error_handler as ERROR_HANDLER
from .info import HELP_HANDLER, START_HANDLER
from .load_journal import LOAD_HANDLER, LOAD_CALLBACK_HANDLER
from .survey import SURVEY_CONVO_HANDLER
from .webhooks import ALARM_HOOK_HANDLER, REPORT_HOOK_HANDLER


ALL_COMMAND_HANDLERS: list[BaseHandler] = [
    ALARM_CONVO_HANDLER,
    ALARM_CANCEL_HANDLER,
    START_HANDLER,
    HELP_HANDLER,
    LOAD_HANDLER,
    LOAD_CALLBACK_HANDLER,
    SURVEY_CONVO_HANDLER,
    ALARM_HOOK_HANDLER,
    REPORT_HOOK_HANDLER,
]
